pipeline {
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Build Docker') {
            steps {
                script {
                    sh '''
                    echo 'Build Docker Image'
                    docker build -t swapnil6799/task:${BUILD_NUMBER} .
                    docker images
                    ''' 
                }
            }
        }

        stage('Docker Login & Push') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: 'docker-login', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                        sh '''
                        echo "Logging in to Docker Registry"
                        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

                        echo 'Push Docker Image'
                        docker push swapnil6799/task:${BUILD_NUMBER}
                        '''
                    }
                }
            }
        }

        stage('SSH into Instance & Run Container') {
            steps {
                script {
                    sshagent(['ssh-key']) {
                        sh """
                        echo 'Connecting to Instance and Running Container'
                        ssh -o StrictHostKeyChecking=no ec2-user@3.111.171.6 << 'EOF'

                        echo "Pulling Docker Image"
                        docker pull swapnil6799/task:${BUILD_NUMBER}

                        echo "Running Docker Container"
                        docker run -d --name task-container swapnil6799/task:${BUILD_NUMBER}

                        echo "Docker Container is running on the EC2 instance"
                        EOF
                        """
                    }
                }
            }
        }
    }
}
